### ISSUE TITLE
ValueError: could not convert string to float: 'avg'

### ISSUE THREAD

**Issue by edwardtam68** [Franck-Dernoncourt/NeuroNER#122]
Tried to use NeuroNER on both Windows and Linux platforms.
Found that it worked on Windows while failed on Linux, with this error:

```
Generating plots for the train set
Traceback (most recent call last):
  File "main.py", line 251, in <module>
    main()
  File "main.py", line 247, in main
    nn.fit()
  File "/home/edward/Documents/NeuroNER-master/src/neuroner.py", line 396, in fit
    evaluate.evaluate_model(results, dataset, y_pred, y_true, stats_graph_folder, epoch_number, epoch_start_time, output_filepaths, parameters)
  File "/home/edward/Documents/NeuroNER-master/src/evaluate.py", line 239, in evaluate_model
    verbose=verbose)
  File "/home/edward/Documents/NeuroNER-master/src/evaluate.py", line 22, in assess_model
    cmap='RdBu')
  File "/home/edward/Documents/NeuroNER-master/src/utils_plots.py", line 153, in plot_classification_report
    v = [float(x)*100 for x in t[1: len(t) - 1]]
  File "/home/edward/Documents/NeuroNER-master/src/utils_plots.py", line 153, in <listcomp>
    v = [float(x)*100 for x in t[1: len(t) - 1]]
ValueError: could not convert string to float: 'avg'
```

Traced the program flow and checked the contents of "classification_report" during execution.
The error was due to changed contents in different versions of classification_report.

Platform | python module "scikit-learn" version | utils_plots.py
-------- | -------- | ---------
Windows 10 | 0.19.2 | WORKED OK
Ubuntu 16.04 LTS | 0.20.0 | FAILED

scikit-learn version 0.18 / 0.19
http://scikit-learn.org/0.18/modules/generated/sklearn.metrics.classification_report.html

```
    class 0       0.50      1.00      0.67         1
    class 1       0.00      0.00      0.00         1
    class 2       1.00      0.67      0.80         3

avg / total       0.70      0.60      0.61         5
```

scikit-learn version 0.20
http://scikit-learn.org/stable/modules/generated/sklearn.metrics.classification_report.html

```
     class 0       0.50      1.00      0.67         1
     class 1       0.00      0.00      0.00         1
     class 2       1.00      0.67      0.80         3

   micro avg       0.60      0.60      0.60         5
   macro avg       0.50      0.56      0.49         5
weighted avg       0.70      0.60      0.61         5
```

Therefore the following code change is proposed:

```
utils_plots.py (line 146) 
            # t = line.strip().replace('avg / total', 'micro-avg').split() # for scikit-learn 0.19.0
            t = line.strip().replace(' avg', '-avg').split() # for scikit-learn 0.20.0
```

Hope this helps.

**Comment by zoiewong** [comment]
Very useful! thank you Edward

**Comment by Juanvulcano** [comment]
Tested on MacOs 10.13.5, ! it is also failing.
Your code change worked, now I am getting:

  File "main.py", line 251, in <module>
    main()
  File "main.py", line 247, in main
    nn.fit()
  File "/Users/juanverhook/Gaia/NeuroNER-master/src/neuroner.py", line 394, in fit
    evaluate.evaluate_model(results, dataset, y_pred, y_true, stats_graph_folder, epoch_number, epoch_start_time, output_filepaths, parameters)
  File "/Users/juanverhook/Gaia/NeuroNER-master/src/evaluate.py", line 239, in evaluate_model
    verbose=verbose)
  File "/Users/juanverhook/Gaia/NeuroNER-master/src/evaluate.py", line 22, in assess_model
    cmap='RdBu')
  File "/Users/juanverhook/Gaia/NeuroNER-master/src/utils_plots.py", line 162, in plot_classification_report
    heatmap(np.array(plotMat), title, xlabel, ylabel, xticklabels, yticklabels, figure_width, figure_height, correct_orientation, cmap=cmap)
  File "/Users/juanverhook/Gaia/NeuroNER-master/src/utils_plots.py", line 112, in heatmap
    show_values(c, fmt=fmt)
  File "/Users/juanverhook/Gai
AttributeError: 'PolyCollection' object has no attribute 'get_axes'
