### ISSUE TITLE
an error occurs when I use i2b2 dataset

### ISSUE THREAD

**Issue by MinLiAmoy** [Franck-Dernoncourt/NeuroNER#53]
Hi,
I have tried the data in conll 2013 and all things work well.
But when I try to use i2b2 dataset, an error occurs. The log is:
Traceback (most recent call last):
```
  File "main.py", line 250, in <module>
    main()
  File "main.py", line 246, in main
    nn.fit()
  File "/home/ubuntu/hang/NeuroNER/src/neuroner.py", line 395, in fit
    evaluate.evaluate_model(results, dataset, y_pred, y_true, stats_graph_folder, epoch_number, epoch_start_time, output_filepaths, parameters)
  File "/home/ubuntu/hang/NeuroNER/src/evaluate.py", line 239, in evaluate_model
    verbose=verbose)
  File "/home/ubuntu/hang/NeuroNER/src/evaluate.py", line 17, in assess_model
    classification_report = sklearn.metrics.classification_report(y_true, y_pred, labels=labels, target_names=target_names, sample_weight=None, digits=4)
  File "/usr/local/lib/python3.5/dist-packages/sklearn/metrics/classification.py", line 1428, in classification_report
    for v in (np.average(p, weights=s),
  File "/usr/local/lib/python3.5/dist-packages/numpy/lib/function_base.py", line 1140, in average
    "Weights sum to zero, can't be normalized")
ZeroDivisionError: Weights sum to zero, can't be normalized
```
It seems like the Weights are all zero when called the function np.average()
Thanks!

**Comment by datoweiss** [comment]
I am having the same issue, was wondering what you ended up doing to resolve this?
