### ISSUE TITLE
KeyError: 'label'

### ISSUE THREAD

**Issue by yinghuaxuehai** [Franck-Dernoncourt/NeuroNER#62]

**Comment by spate141** [comment]
Having a same error! Any solution? or am I missing something here?
```
NeuroNER version: 1.0-dev
TensorFlow version: 1.3.0
{'character_embedding_dimension': 25,
 'character_lstm_hidden_state_dimension': 25,
 'check_for_digits_replaced_with_zeros': 1,
 'check_for_lowercase': 1,
 'dataset_text_folder': '../data/ner_25',
 'debug': 0,
 'dropout_rate': 0.5,
 'experiment_name': 'test',
 'freeze_token_embeddings': 0,
 'gradient_clipping_value': 5.0,
 'learning_rate': 0.005,
 'load_all_pretrained_token_embeddings': 0,
 'load_only_pretrained_token_embeddings': 0,
 'main_evaluation_mode': 'conll',
 'maximum_number_of_epochs': 100,
 'number_of_cpu_threads': 8,
 'number_of_gpus': 0,
 'optimizer': 'sgd',
 'output_folder': '../output',
 'parameters_filepath': './parameters.ini',
 'patience': 10,
 'plot_format': 'pdf',
 'pretrained_model_folder': '../trained_models/conll_2003_en',
 'reload_character_embeddings': 1,
 'reload_character_lstm': 1,
 'reload_crf': 1,
 'reload_feedforward': 1,
 'reload_token_embeddings': 1,
 'reload_token_lstm': 1,
 'remap_unknown_tokens_to_unk': 1,
 'spacylanguage': 'en',
 'tagging_format': 'bioes',
 'token_embedding_dimension': 100,
 'token_lstm_hidden_state_dimension': 100,
 'token_pretrained_embedding_filepath': '../data/word_vectors/glove.6B.100d.txt',
 'tokenizer': 'spacy',
 'train_model': 1,
 'use_character_lstm': 1,
 'use_crf': 1,
 'use_pretrained_model': 0,
 'verbose': 0}
Traceback (most recent call last):
  File "main.py", line 250, in <module>
    main()
  File "main.py", line 245, in main
    nn = NeuroNER(**arguments)
  File "/Users/Snehal/NeuroNER-master/src/neuroner.py", line 259, in __init__
    dataset_filepaths, dataset_brat_folders = self._get_valid_dataset_filepaths(parameters)
  File "/Users/Snehal/NeuroNER-master/src/neuroner.py", line 160, in _get_valid_dataset_filepaths
    conll_to_brat.conll_to_brat(dataset_filepaths[dataset_type], dataset_compatible_with_brat_filepath, dataset_brat_folders[dataset_type], dataset_brat_folders[dataset_type])
  File "/Users/Snehal/NeuroNER-master/src/conll_to_brat.py", line 236, in conll_to_brat
    output_entities(brat_output_folder, previous_filename, entities, text_filepath, text, overwrite=overwrite)
  File "/Users/Snehal/NeuroNER-master/src/conll_to_brat.py", line 113, in output_entities
    output_file.write('T{0}\t{1} {2} {3}\t{4}\n'.format(i+1, entity['label'], entity['start'], entity['end'], 
KeyError: 'label'
Exception ignored in: <bound method NeuroNER.__del__ of <neuroner.NeuroNER object at 0x10153db38>>
Traceback (most recent call last):
  File "/Users/Snehal/NeuroNER-master/src/neuroner.py", line 539, in __del__
    self.sess.close()
AttributeError: 'NeuroNER' object has no attribute 'sess'
```

**Comment by mcavdar** [comment]
It seems that there is a problem with dataset format. Can you provide further details with verbose and debug options?

**Comment by ahmaurya** [comment]
I faced this problem because my labels were not in the BIO formar. For example, it should be B-PER, I-PER, etc. instead of just PER.

**Comment by Parvez-Khan-1** [comment]
I had the same issue and the actual Problem is - In conll_to_brat.py line 113 sometimes the entity dict is empty and we are directly searching for the key label which is not there in the dict it throwing key Error. 

Solution add one if condition to check entity dict  should not be empty
