### ISSUE TITLE
AttributeError: 'PolyCollection' object has no attribute 'get_axes'

### ISSUE THREAD

**Issue by penny9287** [Franck-Dernoncourt/NeuroNER#76]
Generating plots for the train set
Traceback (most recent call last):
  File "main.py", line 250, in <module>
    main()
  File "main.py", line 246, in main
    nn.fit()
  File "/home/panyr/PycharmProjects/NeuroNER-master/src/neuroner.py", line 394, in fit
    evaluate.evaluate_model(results, dataset, y_pred, y_true, stats_graph_folder, epoch_number, epoch_start_time, output_filepaths, parameters)
  File "/home/panyr/PycharmProjects/NeuroNER-master/src/evaluate.py", line 239, in evaluate_model
    verbose=verbose)
  File "/home/panyr/PycharmProjects/NeuroNER-master/src/evaluate.py", line 22, in assess_model
    cmap='RdBu')
  File "/home/panyr/PycharmProjects/NeuroNER-master/src/utils_plots.py", line 162, in plot_classification_report
    heatmap(np.array(plotMat), title, xlabel, ylabel, xticklabels, yticklabels, figure_width, figure_height, correct_orientation, cmap=cmap)
  File "/home/panyr/PycharmProjects/NeuroNER-master/src/utils_plots.py", line 112, in heatmap
    show_values(c, fmt=fmt)
  File "/home/panyr/PycharmProjects/NeuroNER-master/src/utils_plots.py", line 36, in show_values
    ax = pc.get_axes()
AttributeError: 'PolyCollection' object has no attribute 'get_axes'

I cannot deal with this problem T^T

**Comment by penny9287** [comment]
change 'ax = pc.get_axes()' to 'ax = pc.axes' will work !

**Comment by tompollard** [comment]
This issue is fixed in https://github.com/Franck-Dernoncourt/NeuroNER/pull/79
