### ISSUE TITLE
ImportError: No module named 'pycorenlp'

### ISSUE THREAD

**Issue by KanimozhiU** [Franck-Dernoncourt/NeuroNER#77]
Traceback (most recent call last):
  File "main.py", line 13, in <module>
    from neuroner import NeuroNER
  File "/home/user/NeuroNER-master/src/neuroner.py", line 8, in <module>
    from pycorenlp import StanfordCoreNLP
ImportError: No module named 'pycorenl

Requirement already up-to-date: pycorenlp in /usr/local/lib/python2.7/dist-packages
Requirement already up-to-date: requests in /usr/local/lib/python2.7/dist-packages (from pycorenlp)
Requirement already up-to-date: urllib3<1.23,>=1.21.1 in /usr/local/lib/python2.7/dist-packages (from requests->pycorenlp)
Requirement already up-to-date: idna<2.7,>=2.5 in /usr/local/lib/python2.7/dist-packages (from requests->pycorenlp)
Requirement already up-to-date: chardet<3.1.0,>=3.0.2 in /usr/local/lib/python2.7/dist-packages (from requests->pycorenlp)
Requirement already up-to-date: certifi>=2017.4.17 in /usr/local/lib/python2.7/dist-packages (from requests->pycorenlp)

**Comment by grafael** [comment]
Install the missing package.
Try: `sudo pip install pycorenlp`

**Comment by KanimozhiU** [comment]
Tried, sudo pip install pycorenlp and updated numpy. This is the error it throws

RuntimeError: module compiled against API version 0xa but this version of numpy is 0x9
Traceback (most recent call last):
  File "main.py", line 13, in <module>
    from neuroner import NeuroNER
  File "/home/user/Documents/NeuroNER-master/src/neuroner.py", line 3, in <module>
    import train
  File "/home/user/Documents/NeuroNER-master/src/train.py", line 2, in <module>
    import tensorflow as tf
  File "/home/user/.local/lib/python3.5/site-packages/tensorflow/__init__.py", line 24, in <module>
    from tensorflow.python import *
  File "/home/user/.local/lib/python3.5/site-packages/tensorflow/python/__init__.py", line 49, in <module>
    from tensorflow.python import pywrap_tensorflow
  File "/home/user/.local/lib/python3.5/site-packages/tensorflow/python/pywrap_tensorflow.py", line 41, in <module>
    from tensorflow.python.pywrap_tensorflow_internal import *
  File "/home/user/.local/lib/python3.5/site-packages/tensorflow/python/pywrap_tensorflow_internal.py", line 28, in <module>
    _pywrap_tensorflow_internal = swig_import_helper()
  File "/home/user/.local/lib/python3.5/site-packages/tensorflow/python/pywrap_tensorflow_internal.py", line 24, in swig_import_helper
    _mod = imp.load_module('_pywrap_tensorflow_internal', fp, pathname, description)
  File "/home/user/anaconda3/lib/python3.5/imp.py", line 243, in load_module
    return load_dynamic(name, filename, file)
  File "/home/user/anaconda3/lib/python3.5/imp.py", line 343, in load_dynamic
    return _load(spec)
SystemError: initialization of _pywrap_tensorflow_internal raised unreported exception

Kindly, help me out!

**Comment by grafael** [comment]
I recommend running the installation script. There are scripts for Windows, Ubuntu and MacOS. Also installing under virtualenv can prevent packages conflict.

**Comment by tompollard** [comment]
The instructions (e.g. https://github.com/Franck-Dernoncourt/NeuroNER/blob/master/install_mac.md) explain how to install dependencies:

> sudo pip3 install -U networkx matplotlib scikit-learn scipy spacy pycorenlp

A requirements file is added in https://github.com/Franck-Dernoncourt/NeuroNER/pull/130
