### ISSUE TITLE
Error in running NeuroNER

### ISSUE THREAD

**Issue by pengyubio** [Franck-Dernoncourt/NeuroNER#82]
I got the following error when running NeuroNER Mac OS X. Does anybody know what is wrong? Thanks.

```
~/NeuroNER/src$ python3 main.py 
NeuroNER version: 1.0-dev
TensorFlow version: 1.4.0
Traceback (most recent call last):
  File "main.py", line 250, in <module>
    main()
  File "main.py", line 245, in main
    nn = NeuroNER(**arguments)
  File "/xxx/NeuroNER/src/neuroner.py", line 257, in __init__
    parameters, conf_parameters = self._load_parameters(arguments['parameters_filepath'], arguments=arguments)
  File "/xxx/NeuroNER/src/neuroner.py", line 118, in _load_parameters
    parameters[k] = distutils.util.strtobool(v)
AttributeError: module 'distutils' has no attribute 'util'
Exception ignored in: <bound method NeuroNER.__del__ of <neuroner.NeuroNER object at 0x102268c18>>
Traceback (most recent call last):
  File "/xxx/NeuroNER/src/neuroner.py", line 489, in __del__
    self.sess.close()
AttributeError: 'NeuroNER' object has no attribute 'sess'
```

**Comment by JohnGiorgi** [comment]
Asked & answered in #75.

**Comment by pengyu** [comment]
OK. Problem solved.

How to close the issue?
