### ISSUE TITLE
KeyError: 'pretrained_model_folder' on default conll 2003 model

### ISSUE THREAD

**Issue by hprovenza** [Franck-Dernoncourt/NeuroNER#97]
(tensorflow) Hannahs-MacBook-Pro:NeuroNER-master hannahprovenza$ python src/main.py
NeuroNER version: 1.0-dev
TensorFlow version: 1.1.0
{'character_embedding_dimension': 25,
 'character_lstm_hidden_state_dimension': 25,
 'check_for_digits_replaced_with_zeros': 1,
 'check_for_lowercase': 1,
 'dataset_text_folder': '../data/conll2003/en',
 'debug': 0,
 'dropout_rate': 0.5,
 'experiment_name': 'test',
 'freeze_token_embeddings': 0,
 'gradient_clipping_value': 5.0,
 'learning_rate': 0.005,
 'load_all_pretrained_token_embeddings': 0,
 'load_only_pretrained_token_embeddings': 0,
 'main_evaluation_mode': 'conll',
 'maximum_number_of_epochs': 100,
 'number_of_cpu_threads': 8,
 'number_of_gpus': 0,
 'optimizer': 'sgd',
 'output_folder': '../output',
 'parameters_filepath': './parameters.ini',
 'patience': 10,
 'plot_format': 'pdf',
 'pretrained_model_folder': '../trained_models/conll_2003_en',
 'reload_character_embeddings': 1,
 'reload_character_lstm': 1,
 'reload_crf': 1,
 'reload_feedforward': 1,
 'reload_token_embeddings': 1,
 'reload_token_lstm': 1,
 'remap_unknown_tokens_to_unk': 1,
 'spacylanguage': 'en',
 'tagging_format': 'bioes',
 'token_embedding_dimension': 100,
 'token_lstm_hidden_state_dimension': 100,
 'token_pretrained_embedding_filepath': '../data/word_vectors/glove.6B.100d.txt',
 'tokenizer': 'spacy',
 'train_model': 1,
 'use_character_lstm': 1,
 'use_crf': 1,
 'use_pretrained_model': 0,
 'verbose': 0}
Traceback (most recent call last):
  File "src/main.py", line 250, in <module>
    main()
  File "src/main.py", line 245, in main
    nn = NeuroNER(**arguments)
  File "/Users/hannahprovenza/Development/duolingo/NeuroNER-master/src/neuroner.py", line 257, in __init__
    parameters, conf_parameters = self._load_parameters(arguments['parameters_filepath'], arguments=arguments)
  File "/Users/hannahprovenza/Development/duolingo/NeuroNER-master/src/neuroner.py", line 132, in _load_parameters
    conf_parameters.set(parameter_to_section[k], k, str(v))
KeyError: 'pretrained_model_folder'

**Comment by hprovenza** [comment]
Fixed - need to run from src directory, not NeuroNER-master directory
